<h1 class="rtecenter">Uslovi garancije</h1>

<h2 class="rtecenter">Garancija</h2>
<p class="rtejustify">
    Izjavljujemo da će kupljeni proizvod za koji je izdata garancija o saobraznosti funkcionisati ispravno ukoliko se njima rukuje prema uputstvu i tehničkim specifikacijama koje na te proizvode daje proizvođač. Obavezujemo se da ćemo na zahtev izražen u garantnom roku u našem ili ovlašćenom servisu otkloniti svaku nesaobraznost proizvoda nastalu normalnim korišćenjem uređaja. Garantni rok počinje od dana kupovine proizvoda, što dokazujete overenim garantnim listom i fiskalnim računom, a traje onoliko koliko je meseci navedeno uz svaki uređaj. Minimalno trajanje garancije na saobraznost uređaja (za fizička lica, koja uređaj isključivo koriste u nekomercijalne svrhe) je 24 meseca. Ostupanje od ovog pravila je garancija na saobraznost na potrošni materijal uređaja kao što su: razne vrste baterija, tonera, kertridža, glava štampača i ostalih delova uređaja koji se smatraju potrošnim materijalom, na iste garancija može biti manja od 24 meseca i obično je definisana posebnim pravilima koja propisuje proizvođač. Ukoliko nesaobraznost ne budu otklonjena u razumnom roku, obavezujemo se da ćemo uređaj na zahtev kupca zameniti odgovarajućim ispravnim. Ukoliko u datom trenutku uređaj nije tržišno raspoloživ, zamena će se izvršiti za neki adekvatan uređaj uz razliku u ceni po vežećem cenovniku. Ako i to nije moguće izvršićemo povraćaj novca. Boravak uređaja na servisu ne utiče na dužinu garancije kao ni ugradnja delova. Ukoliko garancija važi za ceo računar, ne može se ostvarivati pravo reklamacije na pojedinačne komponente koje su sačinjavale dati računar. Garancija važi isključivo na saobraznost uređaja, a ne na eventualnu očekivanu funkcionalnost, dakle podrazumevamo da je kupac upoznat sa tehničkim specifikacijama uređaja i u skladu sa tim ne garantujemo da će oprema zadovoljiti kupca ili da je podesna za određenu namenu. Garancija se ne odnosi na poslove redovnog održavanja računara (čišćenje, podmazivanje, itd.) i od korisnika se očekuje da računar ili druge uređaje ne izlaže štetnim dejstvima (duvanski dim, ekstremno prašnjave prostorije, elektromagnetni talasi, hladne ili tople prostorije, itd.). Sve eventualne nepravilnosti prouzrokovane ovakvim i slčnim radnjama nisu obuhvaćene garancijom o saobraznosti.
</p>

<h2 class="rtecenter">Posebni uslovi garancije</h2>
<p class="rtejustify">
    Priznavanje prava na nesaobraznost a u skladu sa Zakonom o zaštiti potrošača je isključivo i diskreciono pravo servisa eXelence d.o.o., odnosno ovlašćenog servisa. U tom smislu, ova garantna izjava je ništavna u sledećim slučajevima: ako se kupac nije pridržavao proizvođačkog uputstva i tehničke specifikacije o upotrebi proizvoda ili ako je na drugi način nestručno ili nepažljivo postupao sa proizvodom; ako je uklonjena ili oštećena garantna nalepnica na proizvodu ili se na drugi način ustanovi da je proizvod otvarala ili servisirala neovlašćena osoba; ako su u proizvod bili ugrađeni ili ako su kao repromaterijal korišćeni neodgovarajući delovi; oštećenja zbog neispravne montaže ili održavanja, oštećenja nastala prilikom transporta nakon isporuke kao i ostala.
</p>
